### ISSUE TITLE
Version 2.41.0 - debug commands no longer work.

### ISSUE THREAD

**Issue by rrirower** [rokucommunity/vscode-brightscript-language#491]
I upgraded to 2.41.0 this morning.  I tried to debug some code and set a breakpoint.  When the code stopped on the breakpoint, it did not allow me to step over, or, step into a function.  Additionally, the debugger would not display variable values and it appeared like the debugger may have been hung since I noticed that the "Variables" panel in the top left of the debugger displays a progress spinner.  The debugger eventually exited on its own.

Downgrading to 2.40.4 allowed me to work in the debugger.

**Comment by TwitchBronBron** [comment]
Which debugger are you using? debug protocol (`enableDebugProtocol: true` in launch.json) or telnet?

**Comment by rrirower** [comment]
Using Visual Studio code with the following launch.json:

  "version": "0.2.0",
    "configurations": [
        {
            "name": "BrightScript Debug: Launch",
            "type": "brightscript",
            "request": "launch",
            "host": "xx.xx.xx.xx",
            "password": "xxxxxxxxx",
            "rootDir": "${workspaceFolder}"
        }
    ]

**Comment by TwitchBronBron** [comment]
Can you please try launching it with these settings, then include the log files it produces (from the `./logs` folder) so I can review what's happening? Be sure to sanitize any sensitive information from the logs before uploading them. 

```jsonc
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "BrightScript Debug: Launch",
            "type": "brightscript",
            "request": "launch",
            "host": "xx.xx.xx.xx",
            "password": "xxxxxxxxx",
            "rootDir": "${workspaceFolder}",
            "logLevel": "trace",
            "fileLogging": true,
        }
    ]
}
```

**Comment by rrirower** [comment]
I added the two extra lines you specified to the launch manifest.  The debugger allowed me to step through code and look at variables.  I then removed the two lines and I'm back to the same problem above.  Additionally, late yesterday, Visual Studio updated to:

![Capture](https://github.com/rokucommunity/vscode-brightscript-language/assets/34550407/f5b8b058-5f01-4497-b8b1-ad28607574a7)

Do you still need me to upload the logs?

**Comment by TwitchBronBron** [comment]
I found a way to reproduce the issue this morning, i'm working on a fix that should be released in the next few hours. So nope, you're good. Sorry for the trouble!

**Comment by rrirower** [comment]
No worries.  Thanks for the follow up.

**Comment by TwitchBronBron** [comment]
This has been fixed in vscode extension release 2.41.1

![image](https://github.com/rokucommunity/vscode-brightscript-language/assets/2544493/567dfef1-a0b5-40c6-bf56-e108bdd44d8f)

**Comment by rrirower** [comment]
Unfortunately, this update did not resolve my problem.  It still hangs/crashes.  If I revert back to 2.40.4, it works correctly.

**Comment by TwitchBronBron** [comment]
Can you try updating to the latest version of the extension, then rebooting and trying it again? Sometimes vscode doesn't properly unload previous versions during updates.

**Comment by rrirower** [comment]
I updated the extension, reloaded, and re-booted.  Same error.  Debug hangs - no variable evaluation when hovering over a variable and cannot press f10 to step.

**Comment by rrirower** [comment]
This bug has shown itself again.  The only change I've made is to start coding using BrighterScript.  Additionally, the only way I can debug without vscode hanging or crashing is to add the two lines up suggested adding in the prior post [above](https://github.com/rokucommunity/vscode-brightscript-language/issues/491#issuecomment-1624090895).

This may be significant.  I noticed that I get lots of messages from the extension regarding a file path when the debugger hangs.  Let me know if you need the exact text of the message.

**Comment by TwitchBronBron** [comment]
@rrirower I released several bug fixes directly related to this issue. Could you please try release v2.44.1 and let me know if that has solved your issues?

**Comment by rrirower** [comment]
Wil do.  I've had it installed for a day or so.  I'll retest and let you know.

**Comment by rrirower** [comment]
This seems to work.  However, the debugger does quite often exit on its own either during or at the launch of a channel I am debugging.  There's no specific condition that I can tell that causes it.
